const GREEN_LIGHT = '#60ac80';
const GREEN_MEDIUM = '#358155';
const GREEN = '#78ce9c';
const PURPLE = '#6D3581';
const PURPLE_LIGHT = '#8B5E8F';
const ORANGE = '#eb9a00';
const WHITE = '#FFFFFF';
const BLACK = '#000000';
const GRAY = '#707070';
const GRAY_LIGHT = '#676767';
const TRANSPARENT = 'transparent';
const RED = '#EA6D6D';

// App colors
const TEXT_TITLE_APP = GRAY_LIGHT;
const TEXT_TITLE = GRAY;
const ACTION_COLOR = GREEN_LIGHT;
const SECUNDARY_ACTION_COLOR = WHITE;
const PLACEHOLDER_TEXT = GRAY_LIGHT;
const PRIMARY = GREEN_LIGHT;
const SECUNDARY = WHITE;
const INFO = ORANGE;
const BODY_BACKGROUND = WHITE;
const BORDER_COLOR = GRAY;
const BORDER_COLOR_DARK = BLACK;
const ERROR = RED;
const DISABLED = GRAY;

export default {
  GREEN_LIGHT,
  GREEN_MEDIUM,
  GREEN,
  PURPLE,
  PURPLE_LIGHT,
  TEXT_TITLE_APP,
  WHITE,
  ORANGE,
  BLACK,
  GRAY,
  TEXT_TITLE,
  ACTION_COLOR,
  SECUNDARY_ACTION_COLOR,
  PLACEHOLDER_TEXT,
  PRIMARY,
  SECUNDARY,
  INFO,
  BODY_BACKGROUND,
  BORDER_COLOR,
  BORDER_COLOR_DARK,
  ERROR,
  TRANSPARENT,
  DISABLED,
};
