const GREEN_LIGHT = '#60ac80';
const GREEN_MEDIUM = '#358155';
const GREEN = '#78ce9c';
const PURPLE = 'rgba(109, 53, 129, 0.88)';
const PURPLE_LIGHT = 'rgba(109, 53, 129, 0.18)';
const ORANGE = '#eb9a00';
const ORANGE_LIGHT = 'rgba(235, 154, 0, 0.26)';
const WHITE = '#FFFFFF';
const BLACK = '#000000';
const GRAY = '#727272';
const GRAY_LIGHT = '#d0d0d0';
const TRANSPARENT = 'transparent';
const RED = '#EA6D6D';
const GREEN_OPACITY_LIGHT = 'rgba(120, 180, 145, 0.3)';

// App colors
const TEXT_TITLE_APP = GRAY_LIGHT;
const TEXT_TITLE = GRAY;
const ACTION_COLOR = GREEN_LIGHT;
const SECUNDARY_ACTION_COLOR = WHITE;
const PLACEHOLDER_TEXT = GRAY_LIGHT;
const PRIMARY = GREEN_LIGHT;
const SECUNDARY = WHITE;
const INFO = ORANGE;
const BODY_BACKGROUND = WHITE;
const BORDER_COLOR = GRAY;
const BORDER_COLOR_DARK = BLACK;
const ERROR = RED;
const DISABLED = GRAY_LIGHT;
const CALENDAR_MONTH_TITLE = GREEN_LIGHT;
const CALENDAR_DATE_NAME = GREEN_LIGHT;
const CALENDAR_DATE_SELECTED = 'rgba(96, 172, 128, 0.15)';
const CALENDAR_DATE_BACKGROUND = 'rgba(96, 172, 128, 0.04)';

export default {
  GREEN_OPACITY_LIGHT,
  CALENDAR_DATE_BACKGROUND,
  CALENDAR_DATE_SELECTED,
  CALENDAR_DATE_NAME,
  CALENDAR_MONTH_TITLE,
  GREEN_LIGHT,
  GREEN_MEDIUM,
  GREEN,
  PURPLE,
  PURPLE_LIGHT,
  TEXT_TITLE_APP,
  WHITE,
  ORANGE,
  BLACK,
  GRAY,
  GRAY_LIGHT,
  TEXT_TITLE,
  ACTION_COLOR,
  SECUNDARY_ACTION_COLOR,
  PLACEHOLDER_TEXT,
  PRIMARY,
  SECUNDARY,
  INFO,
  BODY_BACKGROUND,
  BORDER_COLOR,
  BORDER_COLOR_DARK,
  ERROR,
  TRANSPARENT,
  DISABLED,
  ORANGE_LIGHT,
};
